using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Susu.Contracts;

namespace Susu.ContractsGen;

/// <summary>
/// Generates TypeScript declarations from contract types marked with <see cref="TsExportAttribute"/>.
/// Output is deterministic (sorted, LF) so a snapshot test can detect drift between C# and TS.
/// </summary>
public static class TypeScriptGenerator
{
    public const string Banner = "// <auto-generated> by tools/Susu.ContractsGen from src/Susu.Contracts. Do not edit; run `dotnet run --project tools/Susu.ContractsGen`.";

    public static IReadOnlyDictionary<string, string> Generate()
    {
        var assembly = typeof(TsExportAttribute).Assembly;
        var groups = assembly.GetTypes()
            .Select(t => (Type: t, Export: t.GetCustomAttribute<TsExportAttribute>()))
            .Where(x => x.Export is not null)
            .GroupBy(x => x.Export!.Group)
            .ToDictionary(g => g.Key, g => g.Select(x => x.Type).ToList());
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var (group, types) in groups)
        {
            var needed = new SortedDictionary<string, Type>(StringComparer.Ordinal);
            foreach (var type in types) Collect(type, needed);
            var text = new StringBuilder();
            text.Append(Banner).Append('\n');
            if (group == "plugin") text.Append(PluginPreamble);
            else text.Append($"export const UI_VERSION = {ProtocolVersions.Ui};\n").Append(UiCommandConstants());
            foreach (var type in needed.Values) text.Append('\n').Append(Declare(type));
            if (group == "plugin") text.Append(PluginModule);
            files[group == "plugin" ? "susu-plugin.d.ts" : $"{group}.ts"] = text.ToString();
        }
        return files;
    }

    /// <summary>The page-side names of every whitelisted UI command (the host still checks per window).</summary>
    private static string UiCommandConstants()
    {
        var fields = typeof(UiCommands).GetFields(BindingFlags.Public | BindingFlags.Static).Where(f => f.IsLiteral && f.FieldType == typeof(string));
        var text = new StringBuilder("\nexport const UI_COMMANDS = {\n");
        foreach (var field in fields) text.Append($"  {field.Name}: '{field.GetRawConstantValue()}',\n");
        return text.Append("} as const;\n\nexport type UiCommandName = (typeof UI_COMMANDS)[keyof typeof UI_COMMANDS];\n").ToString();
    }

    private static void Collect(Type type, SortedDictionary<string, Type> needed)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (type.IsArray) { Collect(type.GetElementType()!, needed); return; }
        if (type.Assembly != typeof(TsExportAttribute).Assembly || needed.ContainsKey(type.Name)) return;
        if (!type.IsEnum && !type.IsClass) return;
        needed[type.Name] = type;
        if (type.IsEnum) return;
        foreach (var parameter in Constructor(type).GetParameters()) Collect(parameter.ParameterType, needed);
    }

    private static ConstructorInfo Constructor(Type type) => type.GetConstructors().OrderByDescending(c => c.GetParameters().Length).First();

    private static string Declare(Type type)
    {
        if (type.IsEnum)
        {
            var names = type.GetFields(BindingFlags.Public | BindingFlags.Static)
                .Select(f => f.GetCustomAttribute<JsonStringEnumMemberNameAttribute>()?.Name ?? f.Name)
                .Select(n => $"'{n}'");
            return $"export type {type.Name} = {string.Join(" | ", names)};\n";
        }
        var nullability = new NullabilityInfoContext();
        var lines = new StringBuilder($"export interface {type.Name} {{\n");
        foreach (var parameter in Constructor(type).GetParameters())
        {
            var info = nullability.Create(parameter);
            bool optional = parameter.HasDefaultValue || info.WriteState == NullabilityState.Nullable || Nullable.GetUnderlyingType(parameter.ParameterType) is not null;
            string name = JsonNamingPolicy.CamelCase.ConvertName(parameter.Name!);
            lines.Append($"  {name}{(optional ? "?" : "")}: {Map(parameter.ParameterType)};\n");
        }
        return lines.Append("}\n").ToString();
    }

    private static string Map(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (type.IsArray) return $"{Map(type.GetElementType()!)}[]";
        if (type == typeof(string)) return "string";
        if (type == typeof(bool)) return "boolean";
        if (type == typeof(JsonElement)) return "unknown";
        if (type.IsPrimitive || type == typeof(decimal)) return "number";
        if (type.Assembly == typeof(TsExportAttribute).Assembly) return type.Name;
        throw new NotSupportedException($"No TypeScript mapping for {type.FullName}");
    }

    private const string PluginPreamble = """
// Su-Su plugin API v1 CANDIDATE (PLAN 4.3-4.7). Frozen only after the G1 contract probes pass.
export const API_VERSION = 1;

export type PluginErrorKind = 'auth' | 'quota' | 'rate_limited' | 'network' | 'timeout' | 'unsupported_language' | 'bad_response';

/** Throw to report a classified failure; any other exception is treated as bad_response. */
export declare class PluginError extends Error {
  constructor(kind: PluginErrorKind, detail?: unknown);
  readonly kind: PluginErrorKind;
  readonly detail?: unknown;
}

/** Host APIs (PLAN 4.5). Request/response shapes of $http, $ws and $file are completed in F05. */
export interface HostApis {
  $http(request: Record<string, unknown>): Promise<Record<string, unknown>>;
  $store: { get(key: string): Promise<unknown>; set(key: string, value: unknown): Promise<void>; delete(key: string): Promise<void> };
  $log(level: 'debug' | 'info' | 'warn' | 'error', message: string): void;
  $i18n(key: string): string;
}

export interface Context extends HostApis {
  readonly config: Readonly<Record<string, unknown>>;
  readonly signal: AbortSignal;
  readonly lang: { readonly from: string; readonly to: string };
}

""";

    private const string PluginModule = """

/** Shape of main.js's default export: keys are capability functions (PLAN 4.4). */
export interface SusuPlugin {
  translate?(req: TranslateRequest, ctx: Context): AsyncIterable<TranslateChunk> | Promise<TranslateResult>;
  translateBatch?(req: TranslateBatchRequest, ctx: Context): Promise<TranslateBatchResult>;
  dictionary?(req: { word: string }, ctx: Context): Promise<DictionaryResult>;
  detect?(req: { text: string }, ctx: Context): Promise<DetectCandidate[]>;
  ocr?(req: { image: string; lang?: string }, ctx: Context): Promise<OcrResult>;
  tts?(req: { text: string; lang: string; voice?: string }, ctx: Context): Promise<{ audio: string }>;
  asr?(req: AsrRequest, ctx: Context): Promise<AsrResult>;
  vocab?(req: VocabRequest, ctx: Context): Promise<VocabResult>;
  validate?(ctx: Context): Promise<void>;
  voices?(ctx: Context): Promise<Voice[]>;
  options?(req: OptionsRequest, ctx: Context): Promise<OptionsResult>;
}
""";
}
