using System.Text.Json;
using System.Text.Json.Serialization;

namespace Susu.Contracts;

/// <summary>Source-generated (NativeAOT-safe) serialization for every contract type.</summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, AllowOutOfOrderMetadataProperties = false, UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
[JsonSerializable(typeof(IpcEnvelope))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(HelloPayload))]
[JsonSerializable(typeof(ChunkPayload))]
[JsonSerializable(typeof(AckPayload))]
[JsonSerializable(typeof(LoadPayload))]
[JsonSerializable(typeof(LoadedPayload))]
[JsonSerializable(typeof(InvokePayload))]
[JsonSerializable(typeof(ApiCallPayload))]
[JsonSerializable(typeof(ApiResultPayload))]
[JsonSerializable(typeof(CompletedPayload))]
[JsonSerializable(typeof(PluginErrorInfo))]
[JsonSerializable(typeof(CancelPayload))]
[JsonSerializable(typeof(FaultPayload))]
[JsonSerializable(typeof(StatsPayload))]
[JsonSerializable(typeof(PluginLogPayload))]
[JsonSerializable(typeof(ProviderError))]
[JsonSerializable(typeof(TranslateRequest))]
[JsonSerializable(typeof(TranslateChunk))]
[JsonSerializable(typeof(TranslateResult))]
[JsonSerializable(typeof(TranslateBatchRequest))]
[JsonSerializable(typeof(TranslateBatchResult))]
[JsonSerializable(typeof(DictionaryResult))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(DetectCandidate[]))]
[JsonSerializable(typeof(OcrResult))]
[JsonSerializable(typeof(OcrRequest))]
[JsonSerializable(typeof(AsrResult))]
[JsonSerializable(typeof(AsrRequest))]
[JsonSerializable(typeof(FileHandleInfo))]
[JsonSerializable(typeof(TtsResult))]
[JsonSerializable(typeof(OptionsRequest))]
[JsonSerializable(typeof(OptionsResult))]
[JsonSerializable(typeof(VocabRequest))]
[JsonSerializable(typeof(VocabResult))]
[JsonSerializable(typeof(Voice[]))]
[JsonSerializable(typeof(UiEnvelope))]
[JsonSerializable(typeof(TranslationSnapshot))]
[JsonSerializable(typeof(CardPatch))]
[JsonSerializable(typeof(DictionaryEntryView))]
[JsonSerializable(typeof(CommandResult))]
[JsonSerializable(typeof(UiSnapshot))]
[JsonSerializable(typeof(SettingsView))]
[JsonSerializable(typeof(WindowView))]
[JsonSerializable(typeof(TrayView))]
[JsonSerializable(typeof(CaptureView))]
[JsonSerializable(typeof(OcrView))]
[JsonSerializable(typeof(VoiceView))]
[JsonSerializable(typeof(TranscribeView))]
[JsonSerializable(typeof(TranscribeCueView))]
[JsonSerializable(typeof(TranscribeConfirmRequest))]
[JsonSerializable(typeof(TranscribeSwitchRequest))]
[JsonSerializable(typeof(TranscribeExportRequest))]
[JsonSerializable(typeof(ErrorBarView))]
[JsonSerializable(typeof(SpeechStateView))]
[JsonSerializable(typeof(SpeechBarView))]
[JsonSerializable(typeof(SpeakCardRequest))]
[JsonSerializable(typeof(SpeechPlayRequest))]
[JsonSerializable(typeof(FitContentRequest))]
[JsonSerializable(typeof(SettingsSaveRequest))]
[JsonSerializable(typeof(SecretWriteRequest))]
[JsonSerializable(typeof(SecretDeleteRequest))]
[JsonSerializable(typeof(BindAccountRequest))]
[JsonSerializable(typeof(ValidateProviderRequest))]
[JsonSerializable(typeof(ServiceValidationView))]
[JsonSerializable(typeof(ReorderServiceRequest))]
[JsonSerializable(typeof(ServiceConfigRequest))]
[JsonSerializable(typeof(LoadOptionsRequest))]
[JsonSerializable(typeof(OptionsView))]
[JsonSerializable(typeof(PromptSaveRequest))]
[JsonSerializable(typeof(PromptPreviewRequest))]
[JsonSerializable(typeof(PromptPreviewView))]
[JsonSerializable(typeof(NetworkTestRequest))]
[JsonSerializable(typeof(NetworkTestView))]
[JsonSerializable(typeof(SpeechSelectRequest))]
[JsonSerializable(typeof(OcrSaveRequest))]
[JsonSerializable(typeof(CollectRequest))]
[JsonSerializable(typeof(CollectView))]
[JsonSerializable(typeof(VocabSettingsView))]
[JsonSerializable(typeof(VocabExportCommand))]
[JsonSerializable(typeof(VocabResolveRequest))]
[JsonSerializable(typeof(VocabSyncCommand))]
[JsonSerializable(typeof(SubmitTextRequest))]
[JsonSerializable(typeof(ToggleCardRequest))]
[JsonSerializable(typeof(SelectLanguageRequest))]
[JsonSerializable(typeof(TrayOpenRequest))]
[JsonSerializable(typeof(SettingsIssueView[]))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(JsonElement))]
public partial class ContractsJson : JsonSerializerContext;
