namespace Susu.Contracts;

// ---- UI view DTOs (ARCHITECTURE 6). Projections only: no secrets, grants or real file paths. ----

/// <summary>First message to a page after Ready; later changes arrive as Patch/Event.</summary>
[TsExport("ui")]
public sealed record UiSnapshot(WindowView Window, TranslationSnapshot? Translation = null, SettingsView? Settings = null, TrayView? Tray = null,
    CaptureView? Capture = null, ErrorBarView? ErrorBar = null, SpeechStateView? Speech = null, SpeechBarView? SpeechBar = null, OcrView? Ocr = null, VoiceView? Voice = null, TranscribeView? Transcribe = null);

/// <summary>
/// The one player's state as the pages show it (F10.2). Phase: idle, loading (synthesis or download), playing,
/// stopped (ended, stopped by the user, or replaced) or error. Target names what the shell asked to play: "bar" (the
/// pronunciation bar's text), "card:&lt;serviceId&gt;" (a card's read-aloud key) or "card:&lt;serviceId&gt;:&lt;index&gt;"
/// (a dictionary phonetic key). Error: the service failure; Device: the audio output failure (no-device, device-lost,
/// unsupported, failed). Never carries text or paths.
/// </summary>
[TsExport("ui")]
public sealed record SpeechStateView(long Generation, string Phase, string? Target = null, ErrorKind? Error = null, string? Device = null);

/// <summary>
/// The pronunciation bar (DESIGN 9 "发音浮条", PLAN 6.5): one square per usable pronunciation service, the default one
/// first; Active is the service whose playback the bar started last. The spoken text stays in the host.
/// </summary>
[TsExport("ui")]
public sealed record SpeechBarView(long Id, SpeechServiceView[] Services, string Active);

[TsExport("ui")]
public sealed record SpeechServiceView(string Instance, bool Default);

/// <summary>
/// Speech.SpeakCard: read a shown card aloud. Without Phonetic the card's translation is spoken with the default service;
/// with Phonetic (an index into the entry's phonetics) the dictionary's own audio plays when the entry has it, else the
/// word is spoken with the default service. Only a result already on screen is used (TTS03).
/// </summary>
[TsExport("ui")]
public sealed record SpeakCardRequest(string ServiceId, int? Phonetic = null);

/// <summary>Speech.Play (pronunciation bar): speak the bar's text again with one of its services.</summary>
[TsExport("ui")]
public sealed record SpeechPlayRequest(string Instance);

/// <summary>
/// The capture shown in the floating Selection window (F08.3). Origin: "selection" (UIA/IA2/borrow) or "clipboard"
/// (text read from the clipboard). Empty: nothing to translate, so the window waits for input. Never carries text;
/// the text travels in the translation snapshot's SourceText.
/// </summary>
[TsExport("ui")]
public sealed record CaptureView(long Id, string Origin, bool Empty);

/// <summary>
/// The OCR result window (F11.3, DESIGN Ocr artboard). Phase: idle, recognizing, recognized, noText, failed, unavailable or
/// cancelled. Text is the source-card text (blocks one per line, formulas as their LaTeX source); Blocks carry each block's
/// text and kind (text | formula) so formulas can be shown and copied as source. ErrorKind: the provider error class of a
/// failed recognition (auth, quota, network, ...), shown with host texts, never a vendor message. Preview: a small PNG
/// thumbnail as a <c>data:image/png;base64,</c> URL generated by the host (at most <c>PreviewMaxBytes</c> of PNG; null when
/// larger or unavailable) - never a file path or file URL. Width/Height: the captured region in physical pixels.
/// Notice: a capture side note (capture.diskFull / capture.writeFailed for a kept copy that could not be written).
/// AutoTranslate: the SetOcr switch; when off the page offers Translate for the (possibly edited) text. Hotkey: the OCR chord
/// ("" when unassigned) for the status bar hint.
/// </summary>
[TsExport("ui")]
public sealed record OcrView(long Id, string Phase, string? ServiceId, string? Text, OcrBlockView[] Blocks, ErrorKind? ErrorKind, string? Preview,
    int Width, int Height, bool Translated, bool AutoTranslate, string Hotkey, string? Notice = null, long? ElapsedMs = null)
{
    /// <summary>Largest thumbnail PNG sent to a page (bytes before Base64).</summary>
    public const int PreviewMaxBytes = 256 * 1024;
}

[TsExport("ui")]
public sealed record OcrBlockView(string Text, string Kind);

/// <summary>
/// The voice window (F12.3, DESIGN Voice artboard, REC01-REC03). Phase: idle (microphone ready), recording, paused, transcribing,
/// transcribed, noSpeech, failed (the ASR service failed: ErrorKind), unavailable (no usable ASR service), interrupted (the
/// device went away: Reason is deviceRemoved | defaultChanged | sleep | failed, CanTranscribe says whether captured audio is kept)
/// or error (the microphone could not start or the recording could not be saved: ErrorCode is mic.denied, mic.noDevice, mic.failed,
/// mic.busy, record.diskFull or record.writeFailed). ElapsedMs is captured time (a pause does not count) against LimitMs; Level is
/// the 0..1 peak for the meter; Silent shows the "no voice detected" notice. Nothing is transcribed while recording: Text appears
/// only after the recording ended. F13.2: Source is microphone | systemAudio (the same window records either); a system-audio recording sets
/// OwnPlayback, the notice that the captured sound includes Su-Su's own playback (its ErrorCode may be loopback.noDevice, loopback.denied or
/// loopback.failed). Notice: "limit" when the recording stopped at the 10-minute limit. The page never gets audio or a path.
/// </summary>
[TsExport("ui")]
public sealed record VoiceView(long Id, string Phase, long ElapsedMs, long LimitMs, double Level, bool Silent, string? Reason, string? ErrorCode, string? ServiceId,
    string? Text, ErrorKind? ErrorKind, bool Translated, string Hotkey, bool CanTranscribe, string? Notice = null, int? Chunk = null, int? Chunks = null, long? TranscribeMs = null,
    string Source = "microphone", bool OwnPlayback = false);

/// <summary>
/// The Transcribe window (F14.4, DESIGN Transcribe artboard, PLAN 6.2). Phase: idle (no file), picked (file probed: FileName, DurationMs,
/// HasVideo, Streams), pickError (ErrorCode is a media.* code: the file cannot be used), confirm (Upload: what is sent where, answered with
/// Transcription.Confirm), running (Stage probe | asr | translate with SlicesDone of SlicesTotal), paused, quota (QuotaSide asr |
/// translation, Choices: services to switch to), failed (ErrorCode and ErrorKind), cancelled, done. The page never sees a path or a media
/// token. Cues travel as <c>transcribe.cue</c> events (upsert by Id) while a job runs; the snapshot carries the full list; an event view
/// with empty Cues and the same JobId keeps the list the page has. Export is the last export attempt.
/// </summary>
[TsExport("ui")]
public sealed record TranscribeView(long Id, string Phase, string? JobId, string? FileName, long? DurationMs, bool HasVideo, TranscribeStreamView[] Streams,
    string? ErrorCode, ErrorKind? ErrorKind, string Stage, int SlicesDone, int SlicesTotal, int CueCount, int Translated, int FailedCues,
    string? AsrService, string? TranslationService, string? QuotaSide, TranscribeUploadView? Upload, TranscribeChoiceView[] Choices,
    TranscribeCueView[] Cues, TranscribeExportView? Export, string Hotkey);

[TsExport("ui")]
public sealed record TranscribeStreamView(string Codec, int SampleRate, int Channels, bool Decodable, bool Selected);

/// <summary>The upload confirmation (T06): file, services, limits and an upper bound of the upload. Character total and price are null when unknown (never made up).</summary>
[TsExport("ui")]
public sealed record TranscribeUploadView(string FileName, long DurationMs, bool HasVideo, string AsrService, string AsrModel, long UploadBytesEstimate,
    int ChunkSecondsLimit, long ChunkBytesLimit, string TranslationService, string TranslationServiceName, int TranslationMaxInput, int TranslationMaxItems,
    string? QuotaNoteKey, long? EstimatedCharacters, string? EstimatedPrice);

/// <summary>A service to switch to when one ran out of quota. Kind: translation | asr; Model is set for asr.</summary>
[TsExport("ui")]
public sealed record TranscribeChoiceView(string Kind, string Id, string Model, bool Current);

[TsExport("ui")]
public sealed record TranscribeCueView(string Id, double Start, double End, string Original, string? Translation, string? TranslationError);

/// <summary>The last export: Path when saved, Error (export.*) otherwise (Retryable for a full disk), Exported cues written and the cues left out with their code.</summary>
[TsExport("ui")]
public sealed record TranscribeExportView(string Format, string Mode, string? Path, string? Error, bool Retryable, int Exported, int Overlaps, TranscribeIssueView[] Issues);

[TsExport("ui")]
public sealed record TranscribeIssueView(string CueId, string Code);

/// <summary>Transcription.Confirm: the answer to the upload confirmation.</summary>
[TsExport("ui")]
public sealed record TranscribeConfirmRequest(bool Accept);

/// <summary>Transcription.ChangeTranslator: Side translation | asr, the service id (and the ASR model). The choice is saved as the video selection and applied to the job.</summary>
[TsExport("ui")]
public sealed record TranscribeSwitchRequest(string Side, string Id, string Model = "");

/// <summary>Transcription.Export: Format srt | vtt | txt, Mode original | translation | bilingual | bilingualTranslationFirst.</summary>
[TsExport("ui")]
public sealed record TranscribeExportRequest(string Format, string Mode);

/// <summary>
/// The failure bar (DESIGN 9 "悬浮条", Error artboard 01): one 34 DIP row per line near the pointer, gone after 4 s.
/// Key is a UI resource key (texts come from the host resource table, never from a plugin); Link is "settings" or null.
/// </summary>
[TsExport("ui")]
public sealed record ErrorBarView(long Id, ErrorLineView[] Lines);

[TsExport("ui")]
public sealed record ErrorLineView(string Key, string? Link = null);

/// <summary>Window.FitContent: the page's content height in DIPs (CSS px); the host clamps it to the work area.</summary>
[TsExport("ui")]
public sealed record FitContentRequest(int HeightDip);

[TsExport("ui")]
public sealed record WindowView(WindowKind Kind, string UiLanguage, string Theme, bool Maximized, bool Pinned, bool DevPreview, string[] Features);

[TsExport("ui")]
public sealed record TrayView(TrayItemView[] Items);

/// <summary>A tray menu entry; unimplemented or unconfigured features are listed disabled with a reason, never as a dead link.</summary>
[TsExport("ui")]
public sealed record TrayItemView(string Id, string Chord, bool Enabled, string? ReasonKey = null, bool SeparatorBefore = false, string? Status = null);

[TsExport("ui")]
public sealed record SettingsView(
    long Revision,
    string FileHash,
    SettingsIssueView[] Issues,
    GeneralView General,
    HotkeyView[] Hotkeys,
    NetworkView Network,
    ServiceView[] Services,
    AccountView[] Accounts,
    PromptView? Prompt = null,
    SpeechView? Speech = null,
    OcrSettingsView? Ocr = null);

[TsExport("ui")]
public sealed record SettingsIssueView(string Path, string Code, string Message, int Line);

[TsExport("ui")]
public sealed record GeneralView(string UiLanguage, string SourceLanguage, string TargetLanguage, int DefaultExpandedCards, bool AllowClipboardBorrowing, string CloseAction, bool LaunchAtStartup);

/// <summary>State: ok, conflict (in-app), failed (RegisterHotKey refused), unassigned, unavailable (feature not provided).</summary>
[TsExport("ui")]
public sealed record HotkeyView(string Action, string Chord, string State, string? ReasonKey = null);

/// <summary>The proxy password is never sent to a page; only whether one is saved.</summary>
[TsExport("ui")]
public sealed record NetworkView(string ProxyMode, string ProxyHost, int ProxyPort, string ProxyUsername, bool ProxyPasswordSaved, int AiTimeoutSeconds);

/// <summary>Availability: Disabled, MissingCredential, UnsupportedCapability, Ready, TemporarilyUnavailable. Implemented=false: adapter not built yet.</summary>
/// <remarks>
/// CredentialTargets (F06.3a): where each secret will be written under the current config - the service
/// and target shown when the user first enters a key (PLAN 4.5.4). Plan: DeepL's endpoint, "free" or "pro",
/// set by the host from the key's ":fx" suffix. Order: position in the merged translation order (translation and AI
/// services, the order result cards follow), -1 otherwise. UsageThisMonth: local count of characters sent this
/// month (DATA04; not a vendor balance), null when the host does not track the service.
/// </remarks>
/// <remarks>
/// Config (F07.2): the package's manifest config schema with the instance's current values, the controls the
/// page generates; InstanceRevision is what Settings.SaveServiceConfig expects back.
/// </remarks>
[TsExport("ui")]
public sealed record ServiceView(string ServiceId, string InstanceId, string Capability, string Page, bool Enabled, string Availability, bool Implemented, string[] SecretNames, string? AccountId,
    CredentialTargetView[]? CredentialTargets = null, string? Plan = null, int Order = -1, long? UsageThisMonth = null, ConfigFieldView[]? Config = null, long InstanceRevision = 0);

/// <summary>
/// One generated settings control (PLAN 4.6 config schema + x-susu). Type: string | integer | number | boolean.
/// Value: the saved value (absent = the default applies). Dynamic: choices come from Settings.LoadOptions;
/// OptionsRevision is the field's dependency revision, which changes whenever a field, account or address it
/// depends on changes, and a loaded list is only shown while it still matches (CFG02).
/// </summary>
[TsExport("ui")]
public sealed record ConfigFieldView(string Name, string Type, string? Value = null, string? Default = null, string[]? Enum = null, string? Title = null,
    string? Format = null, double? Minimum = null, double? Maximum = null, string? Group = null, string? Placeholder = null, string? Help = null,
    string? ShowWhenField = null, string? ShowWhenEquals = null, bool Dynamic = false, long OptionsRevision = 0);

[TsExport("ui")]
public sealed record ConfigValueView(string Name, string Value);

/// <summary>Settings.SaveServiceConfig: an empty Value clears the field back to its default. Checked against the schema by the host.</summary>
[TsExport("ui")]
public sealed record ServiceConfigRequest(string InstanceId, long ExpectedInstanceRevision, ConfigValueView[] Values);

/// <summary>Settings.LoadOptions: one page of a dynamic field for the dependency revision the page shows.</summary>
[TsExport("ui")]
public sealed record LoadOptionsRequest(string InstanceId, string Field, long DependsOnRevision, string? Cursor = null, bool Refresh = false);

/// <summary>
/// Stale: the field's dependencies changed since DependsOnRevision; the page drops the result. Error: the kind
/// only; the page keeps the current selection. Cached: served from the 5-minute cache.
/// </summary>
[TsExport("ui")]
public sealed record OptionsView(string InstanceId, string Field, long DependsOnRevision, OptionItem[] Items, string? NextCursor = null, bool Cached = false,
    bool Stale = false, ErrorKind? Error = null);

/// <summary>Use: header:Authorization, signer:tencent-tc3, ... Granted: the user confirmed this package, origin and use for the secret.</summary>
[TsExport("ui")]
public sealed record CredentialTargetView(string Secret, string Origin, string Use, bool Saved, bool Granted);

[TsExport("ui")]
public sealed record AccountView(string Id, string Label, SecretSlotView[] Secrets, string[] UsedBy);

/// <summary>Saved is the only thing a page learns about a stored secret.</summary>
[TsExport("ui")]
public sealed record SecretSlotView(string Name, bool Saved);

/// <summary>
/// SetPrompt (F07.3). Level: a built-in level id or "" (none). Profile: the custom template in use or "" (the
/// built-in default). Scope: AI instance ids the prompt is sent to; AiServices lists the choices in display order.
/// Translation engines never receive a prompt.
/// </summary>
[TsExport("ui")]
public sealed record PromptView(string Level, string Profile, string[] Scope, string[] Levels, string[] AiServices, PromptProfileView[] Profiles, string DefaultTemplate, string[] Variables);

[TsExport("ui")]
public sealed record PromptProfileView(string Id, string Name, string Template);

/// <summary>Settings.SavePrompt: the whole SetPrompt page; ExpectedRevision/FileHash guard like Settings.Save.</summary>
[TsExport("ui")]
public sealed record PromptSaveRequest(long ExpectedRevision, string ExpectedFileHash, string Level, string Profile, string[] Scope, PromptProfileView[] Profiles);

/// <summary>Settings.PreviewPrompt: renders Template ("" = the built-in default) exactly as a task would, with a sample text.</summary>
[TsExport("ui")]
public sealed record PromptPreviewRequest(string Template, string Level, string Text, string From, string To);

/// <summary>Unknown: variable names that are not substituted and stay literal. Problem: why the template cannot be saved, or null.</summary>
[TsExport("ui")]
public sealed record PromptPreviewView(string Rendered, string[] Unknown, string? Problem = null);

/// <summary>Settings.TestNetwork: tests the proxy settings being edited (the saved password is used) through the network broker.</summary>
[TsExport("ui")]
public sealed record NetworkTestRequest(NetworkView Network);

/// <summary>
/// Result per path (CFG05). Route: proxy | direct | local (loopback services never use the proxy). Ok: the
/// origin answered (any HTTP status). Error: the kind only (network, timeout, ...). Services: the enabled
/// services on that origin.
/// </summary>
[TsExport("ui")]
public sealed record NetworkPathView(string Origin, string[] Services, string Route, bool Ok, ErrorKind? Error = null, int? Status = null, long ElapsedMs = 0);

[TsExport("ui")]
public sealed record NetworkTestView(NetworkPathView[] Paths, string TestedAt);

[TsExport("ui")]
public sealed record ServiceToggle(string ServiceId, bool Enabled);

[TsExport("ui")]
public sealed record SettingsSaveRequest(long ExpectedRevision, string ExpectedFileHash, GeneralView General, HotkeyView[] Hotkeys, NetworkView Network, ServiceToggle[] Services);

/// <summary>
/// One-way credential write from the Settings window (PLAN 5.4). The value is never echoed back.
/// ConfirmGrants: the user confirmed the service and targets shown with the key field
/// (<see cref="ServiceView.CredentialTargets"/>); the host then grants this secret to the package for the
/// origin/use its config needs after the write (DeepL: the plan follows the key). Without it the key is
/// saved and bound but not usable until <c>Settings.BindAccount</c> confirms.
/// </summary>
[TsExport("ui")]
public sealed record SecretWriteRequest(string InstanceId, string SecretName, string Value, bool ConfirmGrants = false);

/// <summary>
/// Settings.BindAccount: binds the instance's secrets to <paramref name="AccountId"/> (an existing account
/// holding the same secret names, e.g. a shared Tencent Cloud account; null keeps the current binding) and,
/// with ConfirmGrants, grants every credential target the instance currently needs (a changed plan or address).
/// </summary>
[TsExport("ui")]
public sealed record BindAccountRequest(string InstanceId, string? AccountId = null, bool ConfirmGrants = true);

/// <summary>Settings.ValidateProvider: one minimal real call through the configured service, enabled or not.</summary>
[TsExport("ui")]
public sealed record ValidateProviderRequest(string ServiceId);

/// <summary>Credential: valid | invalid | unknown, kept apart from whether the service can be used right now (F06.2a).</summary>
[TsExport("ui")]
public sealed record ServiceValidationView(string ServiceId, string Credential, bool ServiceAvailable, ErrorKind? Error = null);

/// <summary>
/// Settings.ReorderService: moves a service to Index among the services of its own settings page, leaving the
/// other page's slots in place (CFG03). Merged: Index is a position in the merged list of the General page.
/// </summary>
[TsExport("ui")]
public sealed record ReorderServiceRequest(string ServiceId, int Index, bool Merged = false);

[TsExport("ui")]
public sealed record SecretDeleteRequest(string InstanceId, string SecretName);

[TsExport("ui")]
public sealed record SubmitTextRequest(string Text);

[TsExport("ui")]
public sealed record ToggleCardRequest(string ServiceId);

[TsExport("ui")]
public sealed record SelectLanguageRequest(string From, string To);

[TsExport("ui")]
public sealed record TrayOpenRequest(string Id);

/// <summary>
/// SetSpeech/SetSpeechB (F07.4): three selections chosen separately - pronunciation (tts), recording/audio
/// transcription (asr) and video transcription (videoAsr). Changing one never changes another or the AI
/// translation model (A02).
/// </summary>
[TsExport("ui")]
public sealed record SpeechView(SpeechSlotView Tts, SpeechSlotView Asr, SpeechSlotView VideoAsr, string VideoTranslator = "", string[]? VideoTranslatorChoices = null);

/// <summary>
/// One selection. Slot: tts | asr | videoAsr. Instance "" = nothing selected. Choices: the services whose package
/// declares the slot's capability, including ones that cannot be chosen here (Selectable=false with ReasonKey,
/// e.g. needs-timecodes for a text-only ASR under video). Ready: the selected service could run now; it stays
/// false until its package is installed (F10/F12). ReasonKey (when not ready): none-selected, needs-timecodes,
/// not-installed, not-built, missing-credential.
/// </summary>
[TsExport("ui")]
public sealed record SpeechSlotView(string Slot, string Instance, string Model, SpeechChoiceView[] Choices, bool Ready, string? ReasonKey = null);

/// <summary>
/// A listed service. Native: built into Su-Su (SAPI). Installed=false: the plugin package is planned (Plan, e.g.
/// "F12.2 P-R01") but not installed, so it cannot run yet. Availability: as ServiceView (credentials and grants).
/// </summary>
[TsExport("ui")]
public sealed record SpeechChoiceView(string InstanceId, bool Native, bool Installed, string Plan, bool Timecodes, bool Selectable, string Availability,
    SpeechModelView[] Models, string? ReasonKey = null);

/// <summary>Timecodes: the model returns start/end per segment. Selectable=false under video when it does not.</summary>
[TsExport("ui")]
public sealed record SpeechModelView(string Id, bool Timecodes, bool Selectable);

/// <summary>Settings.SelectSpeech: sets one slot only. Refused with needs-timecodes when a text-only model is chosen for video.</summary>
[TsExport("ui")]
public sealed record SpeechSelectRequest(long ExpectedRevision, string ExpectedFileHash, string Slot, string Instance, string Model);

/// <summary>
/// SetOcr (F11.3). Service: the default OCR service; Choices: every OCR service of the catalog (the page lists them with
/// the service-list pattern). Ready: some OCR service can run now (enabled, credentials saved and granted), which is
/// what makes the OCR hotkey and tray entry available; ReasonKey otherwise (feature.noService.ocr). Hotkey: the OCR
/// chord (the same item as SetHotkeys). RetentionDays: MinRetentionDays..MaxRetentionDays.
/// </summary>
[TsExport("ui")]
public sealed record OcrSettingsView(string Service, bool AutoTranslate, bool KeepScreenshots, int RetentionDays, int MinRetentionDays, int MaxRetentionDays,
    OcrChoiceView[] Choices, bool Ready, string Hotkey, string? ReasonKey = null);

/// <summary>An OCR service: whether its capability is enabled, its credential availability (as ServiceView) and whether it could run now.</summary>
[TsExport("ui")]
public sealed record OcrChoiceView(string InstanceId, string ServiceId, bool Enabled, string Availability, bool Usable);

/// <summary>Settings.SaveOcr: the SetOcr fields only (service, auto-translate, keep screenshots, retention days).</summary>
[TsExport("ui")]
public sealed record OcrSaveRequest(long ExpectedRevision, string ExpectedFileHash, string Service, bool AutoTranslate, bool KeepScreenshots, int RetentionDays);
