<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Susu.Tests.Unit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Susu.Abstractions/Susu.Abstractions.csproj" />
    <ProjectReference Include="../Susu.Contracts/Susu.Contracts.csproj" />
  </ItemGroup>
</Project>
