namespace Susu.PluginCli;

/// <summary>
/// `susu-plugin init`: one working starter package per capability. Every template talks to a fictional "Example API" through
/// `ctx.$http`, reads its address from `ctx.config.baseUrl` (the convention that lets `susu-plugin test` point it at the loopback vendor),
/// maps vendor failures to the host's error classes, and comes with a `susu-plugin.test.json` that passes against the real sandbox.
/// </summary>
internal static class Templates
{
    public static readonly string[] Capabilities = ["translate", "dictionary", "detect", "ocr", "tts", "asr", "vocab"];

    private const string Helpers = """
// Maps a vendor HTTP status to the error class the host knows (auth, quota, rate_limited, network, timeout, bad_response).
// The host decides about retries; one Invoke makes one vendor request.
function header(headers, name) {
  if (!headers) return undefined;
  const lower = name.toLowerCase();
  for (const key of Object.keys(headers)) if (key.toLowerCase() === lower) return headers[key];
  return undefined;
}

function classify(status, headers) {
  const detail = `http ${status}`;
  if (status === 401 || status === 403) return new PluginError('auth', detail);
  if (status === 402) return new PluginError('quota', detail);
  if (status === 429) return new PluginError('rate_limited', detail, header(headers, 'retry-after'));
  if (status === 408 || status === 504) return new PluginError('timeout', detail);
  if (status >= 500) return new PluginError('network', detail);
  return new PluginError('bad_response', detail);
}

// The key is never visible to the plugin: the host writes it into the header when the request leaves.
const AUTH = [{ target: { area: 'header', name: 'Authorization' }, parts: [{ literal: 'Bearer ' }, { secret: 'apiKey' }] }];

""";

    private const string Preamble = """
// __NAME__ (__CAPABILITY__), generated by `susu-plugin init`.
// `ctx.config.baseUrl` lets `susu-plugin test` point this at a local stand-in vendor; leave it unset in production.
const DEFAULT_BASE_URL = 'https://api.example.com';

""";

    private const string ManifestHead = """
id: __ID__
name: __NAME__
version: 0.1.0
apiVersion: 1
minHost: 1
entry: main.js
capabilities:
  - __CAPABILITY__
hosts:
  - api.example.com

""";

    private const string ManifestCredentials = """
credentialUse:
  - apiKey

""";

    private const string ManifestConfig = """
config:
  type: object
  properties:
    baseUrl:
      type: string
      format: uri
      title: API address
      x-susu:
        group: advanced
        placeholder: https://api.example.com
        help: Leave empty for the vendor's own address.

""";

    private const string OcrInputs = "      \"inputs\": { \"image\": { \"text\": \"not a real png\", \"mime\": \"image/png\", \"extension\": \"png\", \"width\": 100, \"height\": 50 } },\n";
    private const string AsrInputs = "      \"inputs\": { \"audio\": { \"base64\": \"UklGRg==\", \"mime\": \"audio/wav\", \"extension\": \"wav\", \"durationMs\": 2000 } },\n";

    public static bool IsKeyless(string capability) => capability == "dictionary";

    public static IReadOnlyDictionary<string, string> Files(string capability, string id, string name)
    {
        string manifest = ManifestHead + (IsKeyless(capability) ? "" : ManifestCredentials) + ManifestConfig;
        string main = Preamble + (IsKeyless(capability) ? Helpers.Replace("\n// The key is never visible", "\n// (unused here: this vendor needs no key)\n// The key is never visible") : Helpers) + Body(capability);
        string Fill(string text) => text.Replace("__ID__", id).Replace("__NAME__", name).Replace("__CAPABILITY__", capability);
        return new Dictionary<string, string>
        {
            ["manifest.yaml"] = Fill(manifest),
            ["main.js"] = Fill(main),
            [CaseFile.DefaultName] = Fill(Tests(capability)),
        };
    }

    private static string Body(string capability) => capability switch
    {
        "translate" => """
export default {
  async translate(req, ctx) {
    if (!req || typeof req.text !== 'string' || req.text.length === 0) throw new PluginError('bad_response', 'empty text');
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    const r = await ctx.$http({
      method: 'POST',
      url: `${baseUrl}/v1/translate`,
      headers: { Authorization: '' },
      credentials: AUTH,
      body: { kind: 'json', value: { q: req.text, source: req.from || 'auto', target: req.to || 'en' } },
    });
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    const body = r.body;
    if (!body || typeof body.translation !== 'string') throw new PluginError('bad_response', 'no translation in the response');
    const result = { text: body.translation };
    if (typeof body.detected_source === 'string') result.detectedFrom = body.detected_source;
    return result;
  },
};
""",
        "dictionary" => """
export default {
  async dictionary(req, ctx) {
    const word = req && typeof req.word === 'string' ? req.word.trim() : '';
    if (word.length === 0) throw new PluginError('bad_response', 'empty word');
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    const r = await ctx.$http({ method: 'GET', url: `${baseUrl}/v1/define?word=${encodeURIComponent(word)}` });
    // A word the vendor does not know is an empty entry, not a failure.
    if (r.status === 404) return { word, phonetics: [], parts: [] };
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    const body = r.body;
    if (!body || !Array.isArray(body.senses)) throw new PluginError('bad_response', 'no senses in the response');
    return {
      word: typeof body.word === 'string' ? body.word : word,
      phonetics: (body.phonetics || []).map((p) => ({ accent: p.accent, ipa: p.ipa })),
      parts: body.senses.map((s) => ({ pos: s.pos, means: s.meanings })),
    };
  },
};
""",
        "detect" => """
export default {
  async detect(req, ctx) {
    if (!req || typeof req.text !== 'string' || req.text.length === 0) throw new PluginError('bad_response', 'empty text');
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    const r = await ctx.$http({
      method: 'POST',
      url: `${baseUrl}/v1/detect`,
      headers: { Authorization: '' },
      credentials: AUTH,
      body: { kind: 'json', value: { q: req.text } },
    });
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    if (!r.body || !Array.isArray(r.body.languages)) throw new PluginError('bad_response', 'no languages in the response');
    return r.body.languages.map((l) => ({ lang: l.code, confidence: l.score }));
  },
};
""",
        "ocr" => """
export default {
  async ocr(req, ctx) {
    if (!req || !req.image || typeof req.image.id !== 'string') throw new PluginError('bad_response', 'image handle required');
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    // The plugin never sees the image: it names the JSON field (`/image`) and the host fills it with the Base64 of the leased file.
    const r = await ctx.$http({
      method: 'POST',
      url: `${baseUrl}/v1/ocr`,
      headers: { Authorization: '' },
      credentials: AUTH,
      body: { kind: 'json', value: { image: null, lang: req.lang || 'auto' } },
      bodyFiles: [{ pointer: '/image', file: req.image.id }],
    });
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    if (!r.body || !Array.isArray(r.body.lines)) throw new PluginError('bad_response', 'no lines in the response');
    // Boxes are [x, y, w, h] as fractions of the image (0..1).
    return { blocks: r.body.lines.map((l) => ({ text: l.text, box: [l.x, l.y, l.w, l.h] })) };
  },
};
""",
        "tts" => """
export default {
  async tts(req, ctx) {
    if (!req || typeof req.text !== 'string' || req.text.trim().length === 0) throw new PluginError('bad_response', 'empty text');
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    // The vendor answers JSON with the audio as Base64 in `audio`. The host decodes that field into a file and hands back a
    // handle (`r.files.audio`); the plugin never holds the audio bytes.
    const r = await ctx.$http({
      method: 'POST',
      url: `${baseUrl}/v1/speech`,
      headers: { Authorization: '' },
      credentials: AUTH,
      body: { kind: 'json', value: { text: req.text, voice: req.voice || 'default' } },
      responseFiles: [{ name: 'audio', pointer: '/audio', mime: 'audio/mpeg' }],
    });
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    const audio = r.files && r.files.audio;
    if (!audio || typeof audio.id !== 'string') throw new PluginError('bad_response', 'no audio in the response');
    return { audio };
  },
};
""",
        "asr" => """
export default {
  async asr(req, ctx) {
    if (!req || !req.audio || typeof req.audio.id !== 'string') throw new PluginError('bad_response', 'audio handle required');
    if (req.output !== 'text' && req.output !== 'segments') throw new PluginError('bad_response', `unknown output '${req.output}'`);
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    // The audio goes up as a multipart part the host builds from the leased file; the plugin never sees the bytes.
    const fields = [
      { name: 'file', filename: 'audio.wav', contentType: 'audio/wav', file: req.audio.id },
      { name: 'model', text: req.model || 'default' },
      { name: 'timestamps', text: req.output === 'segments' ? 'true' : 'false' },
    ];
    const r = await ctx.$http({
      method: 'POST',
      url: `${baseUrl}/v1/transcribe`,
      headers: { Authorization: '' },
      credentials: AUTH,
      body: { kind: 'multipart', fields },
    });
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    const body = r.body;
    if (!body || typeof body !== 'object') throw new PluginError('bad_response', 'response is not JSON');
    if (req.output === 'text') {
      if (typeof body.text !== 'string') throw new PluginError('bad_response', 'missing text');
      return { kind: 'text', text: body.text };
    }
    if (!Array.isArray(body.segments)) throw new PluginError('bad_response', 'missing segments');
    // Times are seconds; the host validates them (ordered, inside the audio length) and rejects a bad list.
    return { kind: 'segments', segments: body.segments.map((s) => ({ start: s.start, end: s.end, text: s.text })) };
  },
};
""",
        "vocab" => """
// Maps the vendor's word of what happened to the host's status: applied | found | absent | unknown.
const STATUS = { saved: 'applied', exists: 'found', missing: 'absent' };

export default {
  async vocab(req, ctx) {
    if (!req || typeof req.word !== 'string' || req.word.length === 0) throw new PluginError('bad_response', 'empty word');
    if (req.action !== 'upsert' && req.action !== 'lookup') throw new PluginError('bad_response', `unknown action '${req.action}'`);
    const baseUrl = (ctx.config && ctx.config.baseUrl) || DEFAULT_BASE_URL;
    // operationId is stable for one user action: send it so the vendor can ignore a repeat of the same write.
    const r = await ctx.$http({
      method: 'POST',
      url: `${baseUrl}/v1/words`,
      headers: { Authorization: '' },
      credentials: AUTH,
      body: { kind: 'json', value: { operationId: req.operationId, action: req.action, word: req.word, lang: req.lang } },
    });
    if (r.status < 200 || r.status >= 300) throw classify(r.status, r.headers);
    const body = r.body;
    // An answer that cannot be read after a write is "unknown", never "applied": the host looks it up before it retries.
    if (!body || !STATUS[body.status]) return { status: 'unknown' };
    const result = { status: STATUS[body.status] };
    if (body.id !== undefined && body.id !== null) result.remoteId = String(body.id);
    return result;
  },
};
""",
        _ => throw new ArgumentException($"no template for '{capability}'"),
    };


    private const string ErrorCases = """
    {
      "name": "bad key is an auth error",
      "capability": "__CAPABILITY__",
      "request": __REQUEST__,
__INPUTS__      "secrets": { "apiKey": "wrong" },
      "vendor": [ { "status": 401, "json": { "error": "invalid key" } } ],
      "expect": { "error": "auth", "detailContains": "401" }
    },
    {
      "name": "throttling is rate_limited",
      "capability": "__CAPABILITY__",
      "request": __REQUEST__,
__INPUTS__      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 429, "headers": { "Retry-After": "2" }, "json": {} } ],
      "expect": { "error": "rate_limited" }
    },
    {
      "name": "vendor outage is a network error",
      "capability": "__CAPABILITY__",
      "request": __REQUEST__,
__INPUTS__      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 503, "text": "unavailable" } ],
      "expect": { "error": "network" }
    }
""";

    private static string Tests(string capability)
    {
        (string request, string inputs, string success) = capability switch
        {
            "translate" => ("""{ "text": "hello", "from": "en", "to": "zh-Hans" }""", "", """
    {
      "name": "translates a sentence",
      "capability": "translate",
      "request": { "text": "hello", "from": "en", "to": "zh-Hans" },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "translation": "你好", "detected_source": "en" } } ],
      "expectRequests": [ { "method": "POST", "path": "/v1/translate", "bodyJson": { "q": "hello", "source": "en", "target": "zh-Hans" }, "headerContains": { "Authorization": "Bearer test-key" } } ],
      "expect": { "result": { "text": "你好", "detectedFrom": "en" } }
    },
"""),
            "dictionary" => ("""{ "word": "hello" }""", "", """
    {
      "name": "looks up a word",
      "capability": "dictionary",
      "request": { "word": "hello" },
      "vendor": [ { "status": 200, "json": { "word": "hello", "phonetics": [ { "accent": "us", "ipa": "həˈloʊ" } ], "senses": [ { "pos": "interjection", "meanings": [ "used as a greeting" ] } ] } } ],
      "expectRequests": [ { "method": "GET", "pathContains": "word=hello" } ],
      "expect": { "result": { "word": "hello", "phonetics": [ { "accent": "us", "ipa": "həˈloʊ" } ], "parts": [ { "pos": "interjection", "means": [ "used as a greeting" ] } ] } }
    },
    {
      "name": "an unknown word is an empty entry",
      "capability": "dictionary",
      "request": { "word": "zzzz" },
      "vendor": [ { "status": 404, "json": {} } ],
      "expect": { "result": { "word": "zzzz", "phonetics": [], "parts": [] } }
    },
"""),
            "detect" => ("""{ "text": "bonjour" }""", "", """
    {
      "name": "detects a language",
      "capability": "detect",
      "request": { "text": "bonjour" },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "languages": [ { "code": "fr", "score": 0.98 }, { "code": "ca", "score": 0.01 } ] } } ],
      "expect": { "result": [ { "lang": "fr", "confidence": 0.98 }, { "lang": "ca", "confidence": 0.01 } ] }
    },
"""),
            "ocr" => ("""{ "image": { "$file": "image" }, "lang": "en" }""", OcrInputs, """
    {
      "name": "reads two lines",
      "capability": "ocr",
      "request": { "image": { "$file": "image" }, "lang": "en" },
      "inputs": { "image": { "text": "not a real png", "mime": "image/png", "extension": "png", "width": 100, "height": 50 } },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "lines": [ { "text": "hello", "x": 0.1, "y": 0.1, "w": 0.3, "h": 0.1 }, { "text": "world", "x": 0.1, "y": 0.3, "w": 0.3, "h": 0.1 } ] } } ],
      "expectRequests": [ { "method": "POST", "path": "/v1/ocr", "bodyJson": { "image": "bm90IGEgcmVhbCBwbmc=", "lang": "en" } } ],
      "expect": { "result": { "blocks": [ { "text": "hello", "box": [0.1, 0.1, 0.3, 0.1] }, { "text": "world", "box": [0.1, 0.3, 0.3, 0.1] } ] } }
    },
"""),
            "tts" => ("""{ "text": "hello", "voice": "anna" }""", "", """
    {
      "name": "speaks a word",
      "capability": "tts",
      "request": { "text": "hello", "voice": "anna" },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "audio": "AAECAwQ=" } } ],
      "expectRequests": [ { "method": "POST", "path": "/v1/speech", "bodyJson": { "text": "hello", "voice": "anna" } } ],
      "expect": { "result": { "audio": { "id": "$any", "mime": "audio/mpeg", "bytes": 5 } } }
    },
"""),
            "asr" => ("""{ "audio": { "$file": "audio" }, "model": "default", "output": "text" }""", AsrInputs, """
    {
      "name": "transcribes to text",
      "capability": "asr",
      "request": { "audio": { "$file": "audio" }, "model": "default", "output": "text" },
      "inputs": { "audio": { "base64": "UklGRg==", "mime": "audio/wav", "extension": "wav", "durationMs": 2000 } },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "text": "hello world" } } ],
      "expectRequests": [ { "method": "POST", "path": "/v1/transcribe", "bodyContains": "audio.wav" } ],
      "expect": { "result": { "kind": "text", "text": "hello world" } }
    },
    {
      "name": "transcribes to segments",
      "capability": "asr",
      "request": { "audio": { "$file": "audio" }, "model": "default", "output": "segments" },
      "inputs": { "audio": { "base64": "UklGRg==", "mime": "audio/wav", "extension": "wav", "durationMs": 2000 } },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "segments": [ { "start": 0, "end": 1.5, "text": "hello world" } ] } } ],
      "expect": { "result": { "kind": "segments", "segments": [ { "start": 0, "end": 1.5, "text": "hello world" } ] } }
    },
"""),
            "vocab" => ("""{ "operationId": "op-1", "action": "upsert", "entryRevision": 1, "word": "hello", "lang": "en" }""", "", """
    {
      "name": "saves a word",
      "capability": "vocab",
      "request": { "operationId": "op-1", "action": "upsert", "entryRevision": 1, "word": "hello", "lang": "en" },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "json": { "status": "saved", "id": 42 } } ],
      "expectRequests": [ { "method": "POST", "path": "/v1/words", "bodyJson": { "operationId": "op-1", "word": "hello" } } ],
      "expect": { "result": { "status": "applied", "remoteId": "42" } }
    },
    {
      "name": "an unreadable answer is unknown, not applied",
      "capability": "vocab",
      "request": { "operationId": "op-2", "action": "upsert", "entryRevision": 1, "word": "hello", "lang": "en" },
      "secrets": { "apiKey": "test-key" },
      "vendor": [ { "status": 200, "text": "ok" } ],
      "expect": { "result": { "status": "unknown" } }
    },
"""),
            _ => throw new ArgumentException($"no template for '{capability}'"),
        };
        string errors = IsKeyless(capability)
            ? """
    {
      "name": "vendor outage is a network error",
      "capability": "__CAPABILITY__",
      "request": __REQUEST__,
      "vendor": [ { "status": 503, "text": "unavailable" } ],
      "expect": { "error": "network" }
    }
"""
            : ErrorCases;
        errors = errors.Replace("__REQUEST__", request).Replace("__INPUTS__", inputs);
        return "{\n  \"version\": 1,\n  \"cases\": [\n" + success.TrimEnd('\n') + "\n" + errors + "\n  ]\n}\n";
    }
}
