// Regenerates native/quickjs-bridge/webapis.inc (C string literal) from webapis.js.
// MSVC caps a literal at 16 KB per segment; each source line becomes its own adjacent literal.
import { readFileSync, writeFileSync } from 'node:fs';
const dir = new URL('../native/quickjs-bridge/', import.meta.url);
const lines = readFileSync(new URL('webapis.js', dir), 'utf8').split(/\r?\n/).filter((l) => !/^\s*\/\//.test(l) && l.trim() !== '');
const esc = (l) => '"' + l.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '\\n"';
writeFileSync(new URL('webapis.inc', dir), '// Generated by tools/gen-webapis.mjs from webapis.js. Do not edit.\n' + lines.map(esc).join('\n') + '\n');
