// Generates LICENSES/NOTICE.txt and LICENSES/third-party.json (shown on the About page) from the redistribution inventory (F17.2).
// Usage: node tools/generate-notices.mjs [inventory.json]   (default: docs/evidence/F17/license-inventory-host.json, made by tools/license-inventory.mjs
//        from src/Susu.Host/packages.lock.json). Nothing is invented: every row comes from the inventory, and a license text is included only
//        when a real LICENSE/NOTICE file exists in the package, the pinned source or the installed npm tree. Otherwise the row states the SPDX
//        license from the package metadata and points to the project URL.
import { readFileSync, existsSync, readdirSync, writeFileSync, realpathSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const inventory = JSON.parse(readFileSync(join(root, process.argv[2] ?? 'docs/evidence/F17/license-inventory-host.json'), 'utf8'));
const spdx = (l) => String(l).replace(/^expression:/, '');
const rows = [];
const texts = new Map(); // key -> [{ source, text }]

function readLicense(folder, names, label) {
  const found = [];
  for (const n of names) {
    const p = join(folder, n);
    if (existsSync(p)) found.push({ source: `${label}/${n}`, text: readFileSync(p, 'utf8').replace(/\r\n/g, '\n').trim() });
  }
  return found;
}

for (const p of inventory.nuget.filter((n) => n.redistributed)) {
  const folder = join(root, '.tools', 'nuget', p.id.toLowerCase(), p.version);
  rows.push({ kind: 'nuget', name: p.id, version: p.version, license: spdx(p.license), copyright: p.copyright ?? null, url: p.projectUrl ?? null,
    ships: p.note ?? 'managed assembly compiled into the host' });
  const t = readLicense(folder, p.licenseFiles, `${p.id}/${p.version}`);
  if (t.length) texts.set(`nuget:${p.id}`, t);
}
for (const n of inventory.native) {
  rows.push({ kind: 'native', name: n.name, version: n.version, license: n.license, copyright: null, url: null, ships: n.linkedInto });
}
const deps = JSON.parse(readFileSync(join(root, 'native', 'dependencies.json'), 'utf8'));
const qjs = readLicense(join(root, '.tools', 'quickjs-source', `quickjs-${deps.quickjs.commit}`), ['LICENSE'], `quickjs-ng ${deps.quickjs.tag}`);
if (qjs.length) texts.set('native:QuickJS-NG', qjs);
const webview = readLicense(join(root, '.tools', 'nuget', 'microsoft.web.webview2', '1.0.4191.47'), ['LICENSE.txt', 'NOTICE.txt'], 'Microsoft.Web.WebView2/1.0.4191.47');
if (webview.length) texts.set('native:Microsoft WebView2 loader (static library)', webview);

function npmDir(name, from) {
  const hoisted = join(root, "ui", "node_modules", ".pnpm", "node_modules", name, "package.json");
  if (existsSync(hoisted)) return dirname(realpathSync(hoisted));
  let dir = from;
  while (dir) {
    const candidate = join(dir, 'node_modules', name, 'package.json');
    if (existsSync(candidate)) return dirname(realpathSync(candidate));
    const up = dirname(dir); dir = up === dir ? null : up;
  }
  return null;
}
for (const p of inventory.npm.filter((n) => !n.error)) {
  rows.push({ kind: 'npm', name: p.name, version: p.version, license: p.license, copyright: null, url: null, ships: 'UI bundle (production dependency closure; an upper bound of what Vite includes)' });
  const dir = npmDir(p.name, join(root, 'ui'));
  const t = dir ? readLicense(dir, p.licenseFiles, `${p.name}@${p.version}`) : [];
  if (t.length) texts.set(`npm:${p.name}`, t);
}
rows.sort((a, b) => a.kind.localeCompare(b.kind) || a.name.localeCompare(b.name));

mkdirSync(join(root, 'LICENSES'), { recursive: true });
writeFileSync(join(root, 'LICENSES', 'third-party.json'), JSON.stringify({ components: rows }, null, 2) + '\n');

const out = [];
out.push('Su-Su third-party notices', '',
  'Generated by tools/generate-notices.mjs from docs/evidence/F17/license-inventory-host.json (tools/license-inventory.mjs over src/Susu.Host/packages.lock.json,',
  'native/dependencies.json and the UI production dependencies). Do not edit by hand. A license text is included only when a real file was found; otherwise the',
  'row gives the SPDX license from the package metadata. The .NET runtime notices (MIT) are in the ILCompiler runtime package THIRD-PARTY-NOTICES.TXT.', '',
  'Components', '==========');
for (const r of rows) out.push(`- ${r.name} ${r.version} | ${r.license}${r.copyright ? ` | ${r.copyright}` : ''}${r.url ? ` | ${r.url}` : ''} | ${r.ships}`);
out.push('', 'License texts', '=============');
for (const [key, list] of [...texts.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  for (const t of list) out.push('', `--- ${key} (${t.source}) ---`, t.text);
}
writeFileSync(join(root, 'LICENSES', 'NOTICE.txt'), out.join('\n') + '\n');
console.log(`${rows.length} components, ${texts.size} with license text`);
